services:
  - type: web
    name: removebg-api
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libgl1-mesa-glx libglib2.0-0
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
